config/routes.rb
require 'Nwpadmin'
Rails.application.routes.draw do


  resources :next_steps
  resources :notes
  resources :goals
  resources :attendances
  resources :meetings
  resources :individuals, :has_many => :household_members
  resources :cohorts
  resources :assessments
  resources :organizations
  constraints(Nwpadmin) do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    get '/report' => 'users#report'
  end

  match '/check_code',      to: 'individuals#check_code',        via: 'post'

  devise_for :users

  root 'static_pages#home'
  get 'static_pages/home'

  get 'static_pages/help'

  get 'individual/assign' => 'individuals#assign_cohort', :as => 'assign_cohort'
  get 'individual/assign_to_cohort' => 'individuals#assign_individual_to_cohort', :as => 'assign_individual_to_cohort'
  get 'individual/remove_from_cohort' => 'individuals#remove_individual_from_cohort', :as => 'remove_individual_from_cohort'
  get 'individual/quarterly_report' => 'individuals#quarterly_report', :as => 'quarterly_report'
  get 'individual/update_demographics' => 'individuals#update_demographics', :as => 'update_demographics'

  # Reports
  match '/reports/quarterly', to: "reports#quarterly", via: 'get'

  #constraints(Nwpadmin) do
#    get '/report' => 'users#report'
 # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_paper_trail
  belongs_to :cohort
  has_many :attendances
  has_and_belongs_to_many :individuals
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :verify_is_admin
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :topic, :meeting_date, :cohort_id)
    end
    def verify_is_admin
      (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= simple_form_for(@meeting) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :topic %>
    <%= f.input :meeting_date %>
    <%= f.association :cohort %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Topic</th>
      <th>Meeting date</th>
      <th>Cohort</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %></td>
        <td><%= meeting.topic %></td>
        <td><%= meeting.meeting_date %></td>
        <td><%= meeting.cohort.to_label %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if meeting.attendances.count < 1 %>
          <td><%= link_to 'Record Attendance', new_attendance_path(meeting_id: meeting.id), method: :get %></td>
        <% else %>
          <td><%= link_to 'Show Attendance', attendances_path(meeting_id: meeting.id), method: :get %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @meeting.topic %>
</p>

<p>
  <strong>Meeting date:</strong>
  <%= @meeting.meeting_date %>
</p>

<p>
  <strong>Cohort:</strong>
  <%= @meeting.cohort.to_label %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>