config/routes.rb
require 'Nwpadmin'
Rails.application.routes.draw do


  resources :next_steps
  resources :notes
  resources :goals
  resources :attendances
  resources :meetings
  resources :individuals, :has_many => :household_members
  resources :cohorts
  resources :assessments
  resources :organizations
  constraints(Nwpadmin) do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    get '/report' => 'users#report'
  end

  match '/check_code',      to: 'individuals#check_code',        via: 'post'

  devise_for :users

  root 'static_pages#home'
  get 'static_pages/home'

  get 'static_pages/help'

  get 'individual/assign' => 'individuals#assign_cohort', :as => 'assign_cohort'
  get 'individual/assign_to_cohort' => 'individuals#assign_individual_to_cohort', :as => 'assign_individual_to_cohort'
  get 'individual/remove_from_cohort' => 'individuals#remove_individual_from_cohort', :as => 'remove_individual_from_cohort'
  get 'individual/quarterly_report' => 'individuals#quarterly_report', :as => 'quarterly_report'
  get 'individual/update_demographics' => 'individuals#update_demographics', :as => 'update_demographics'

  # Reports
  match '/reports/quarterly', to: "reports#quarterly", via: 'get'

  #constraints(Nwpadmin) do
#    get '/report' => 'users#report'
 # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/next_step.rb
class NextStep < ApplicationRecord
  belongs_to :goal
end

app/controllers/next_steps_controller.rb
class NextStepsController < ApplicationController
  before_action :verify_is_admin
  before_action :set_next_step, only: [:show, :edit, :update, :destroy]

  # GET /next_steps
  # GET /next_steps.json
  def index
    @next_steps = NextStep.all
  end

  # GET /next_steps/1
  # GET /next_steps/1.json
  def show
  end

  # GET /next_steps/new
  def new
    @next_step = NextStep.new
  end

  # GET /next_steps/1/edit
  def edit
  end

  # POST /next_steps
  # POST /next_steps.json
  def create
    @next_step = NextStep.new(next_step_params)

    respond_to do |format|
      if @next_step.save
        format.html { redirect_to @next_step, notice: 'Next step was successfully created.' }
        format.json { render :show, status: :created, location: @next_step }
      else
        format.html { render :new }
        format.json { render json: @next_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /next_steps/1
  # PATCH/PUT /next_steps/1.json
  def update
    respond_to do |format|
      if @next_step.update(next_step_params)
        format.html { redirect_to @next_step, notice: 'Next step was successfully updated.' }
        format.json { render :show, status: :ok, location: @next_step }
      else
        format.html { render :edit }
        format.json { render json: @next_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /next_steps/1
  # DELETE /next_steps/1.json
  def destroy
    @next_step.destroy
    respond_to do |format|
      format.html { redirect_to next_steps_url, notice: 'Next step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_next_step
      @next_step = NextStep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def next_step_params
      params.require(:next_step).permit(:goal_id, :next_step, :responsible_party, :due_date, :completed)
    end
end

app/helpers/next_steps_helper.rb
module NextStepsHelper
end

app/views/next_steps/_form.html.erb
<%= simple_form_for(@next_step) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :goal %>
    <%= f.input :next_step %>
    <%= f.input :responsible_party %>
    <%= f.input :due_date %>
    <%= f.input :completed %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/next_steps/edit.html.erb
<h1>Editing Next Step</h1>

<%= render 'form', next_step: @next_step %>

<%= link_to 'Show', @next_step %> |
<%= link_to 'Back', next_steps_path %>

app/views/next_steps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Next Steps</h1>

<table>
  <thead>
    <tr>
      <th>Goal</th>
      <th>Next step</th>
      <th>Responsible party</th>
      <th>Due date</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @next_steps.each do |next_step| %>
      <tr>
        <td><%= next_step.goal %></td>
        <td><%= next_step.next_step %></td>
        <td><%= next_step.responsible_party %></td>
        <td><%= next_step.due_date %></td>
        <td><%= next_step.completed %></td>
        <td><%= link_to 'Show', next_step %></td>
        <td><%= link_to 'Edit', edit_next_step_path(next_step) %></td>
        <td><%= link_to 'Destroy', next_step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Next Step', new_next_step_path %>

app/views/next_steps/new.html.erb
<h1>New Next Step</h1>

<%= render 'form', next_step: @next_step %>

<%= link_to 'Back', next_steps_path %>

app/views/next_steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Goal:</strong>
  <%= @next_step.goal %>
</p>

<p>
  <strong>Next step:</strong>
  <%= @next_step.next_step %>
</p>

<p>
  <strong>Responsible party:</strong>
  <%= @next_step.responsible_party %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @next_step.due_date %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @next_step.completed %>
</p>

<%= link_to 'Edit', edit_next_step_path(@next_step) %> |
<%= link_to 'Back', next_steps_path %>