config/routes.rb
require 'Nwpadmin'
Rails.application.routes.draw do


  resources :next_steps
  resources :notes
  resources :goals
  resources :attendances
  resources :meetings
  resources :individuals, :has_many => :household_members
  resources :cohorts
  resources :assessments
  resources :organizations
  constraints(Nwpadmin) do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    get '/report' => 'users#report'
  end

  match '/check_code',      to: 'individuals#check_code',        via: 'post'

  devise_for :users

  root 'static_pages#home'
  get 'static_pages/home'

  get 'static_pages/help'

  get 'individual/assign' => 'individuals#assign_cohort', :as => 'assign_cohort'
  get 'individual/assign_to_cohort' => 'individuals#assign_individual_to_cohort', :as => 'assign_individual_to_cohort'
  get 'individual/remove_from_cohort' => 'individuals#remove_individual_from_cohort', :as => 'remove_individual_from_cohort'
  get 'individual/quarterly_report' => 'individuals#quarterly_report', :as => 'quarterly_report'
  get 'individual/update_demographics' => 'individuals#update_demographics', :as => 'update_demographics'

  # Reports
  match '/reports/quarterly', to: "reports#quarterly", via: 'get'

  #constraints(Nwpadmin) do
#    get '/report' => 'users#report'
 # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/individual.rb
class Individual < ApplicationRecord
  has_paper_trail
  belongs_to :cohort
  belongs_to :organization
  has_and_belongs_to_many :meetings
  has_many :attendances, dependent: :destroy
  has_many :household_members, dependent: :destroy
  has_many :assessments
  has_many :goals, dependent: :destroy
  has_many :notes, dependent: :destroy
  accepts_nested_attributes_for :household_members, allow_destroy: true

  #validates :attribute_name, :presence => {:message => "Customized error message for user."}
  validates :first_name, :presence => true, on: :create
  validates :last_name, :presence => true, on: :create
  validates :address_line_1, :presence => true, on: :create
  validates :city, :presence => true, on: :create
  validates :state, :presence => true, on: :create
  validates :zip, :presence => true, on: :create
  validates :phone_number, :presence => true, on: :create
  validates :mobile_phone_number,  :presence => true, on: :create
  validates :email_address, :presence => true, on: :create
  validates :preferred_method_of_contact, :presence => true, on: :create
  validates :DOB, :presence => true, on: :create
  validates :organization_id, :presence => true, on: :create
  validates :date_of_application, :presence => true, on: :create
  validates :willing_and_able_to_commit_to_program, :presence => true, on: :create
  validates :specific_days_that_do_not_work,  :presence => true, on: :create
  #validates :currently_employed, :presence => true, on: :create
  #validates :how_many_jobs_in_last_six_months,  :presence => true, on: :create
  validates :total_family_income_from_all_sources, :presence => true, on: :create
  #validates :child_support, :presence => true, on: :create
  #validates :currently_file_taxes,  inclusion: { in: [ true, false ] }, on: :create
  validates :highest_education_attained, :presence => true, on: :create
  validates :highest_education_attained_by_parent_or_caretaker,  :presence => true, on: :create
  #validates :marital_status, :presence => true, on: :create
  #validates :parenting_class, :presence => true, on: :create
  #validates :quality_childcare,  :presence => true, on: :create
  #validates :children_currently_in_quality_care, :presence => true, on: :create
  #validates :have_health_care_in_some_form,  inclusion: { in: [ true, false ] }, on: :create
  #validates :children_have_health_care_in_some_form,  inclusion: { in: [ true, false ] }, on: :create
  validates :currently_have_stable_housing,  inclusion: { in: [ true, false ] }, on: :create
  validates :currently_have_reliable_transportation,  inclusion: { in: [ true, false ] }, on: :create
  validates :have_required_auto_insurance, inclusion: { in: [ true, false ] }, on: :create
  validates :have_valid_id_or_drivers_license,  inclusion: { in: [ true, false ] }, on: :create
  #validates :ever_convicted_of_felony, inclusion: { in: [ true, false ] }, on: :create
  #validates :ever_convicted_of_misdemeanor, inclusion: { in: [ true, false ] }, on: :create
  #validates :current_pending_court_cases, inclusion: { in: [ true, false ] }, on: :create
  #validates :any_legal_matters_needing_resolution, inclusion: { in: [ true, false ] }, on: :create
  #validates :have_health_care_in_some_form, inclusion: { in: [ true, false ] }, on: :create
  #validates :children_have_health_care_in_some_form, inclusion: { in: [ true, false ] }, on: :create
  #validates :currently_have_stable_housing, inclusion: { in: [ true, false ] }, on: :create


  enum ethnicity: { "White" => 0, "Hispanic/Latino" => 1, "Black or African American" =>  2, "Asian" => 3, "American Native or Alaska Native" => 4, "Middle Eastern or North African" => 5, "Native Hawaiian or Pacific Islander" => 6, "Other race, ethnicity, or origin" => 7 }
  enum springfield_non_native_population: {"Less than 2,000" => 0, "2,000-9,999" => 1, "10,000-49,000"=>2, "50,000-99,000"=>3, "100,000-249,000"=>4, "250,000 to 1 million"=>5, "Over 1 million"=>6}
  enum springfield_non_native_distance: {"under 25 miles"=>0, "26-50 miles"=>1, "51-100 miles"=>2, "over 100 miles"=>3}
  enum childhood_raisedby_other_than_parents_by_who: {"Grandparent(s)"=>0, "Aunt/Uncle"=>1, "Other relative"=>2, "Not a relative"=>3}

  def self.search(search)
    where("lower(first_name) || lower(last_name)  || phone_number LIKE ?", "%#{search.downcase}%")
  end

  def to_label
    "#{first_name} #{last_name}"
  end

end

app/controllers/individuals_controller.rb
class IndividualsController < ApplicationController
  before_action :verify_is_admin, :except => [:check_code, :new, :create, :show, :edit, :update]
  before_action :set_individual, only: [:show, :edit, :update, :destroy]


  # GET /individuals
  # GET /individuals.json
  def index
    if params[:search]
      @individuals = Individual.search(params[:search]).order("created_at DESC")
      redirect_to individual_path(@individuals.first) if @individuals.count == 1
    else
      @individuals = Individual.all.order('created_at DESC')
    end
  end

  def assign_cohort
    @cohort = Cohort.find(params[:cohort_id])
    @individuals = Individual.where(:cohort_id => nil)
  end

  def quarterly_report
    @cohorts = Cohort.all
    @individuals = Individual.all
  end

  def assign_individual_to_cohort
    @cohort = Cohort.find(params[:cohort_id])
    @Individual = Individual.find(params[:individual_id])
    @Individual.cohort_id = @cohort.id
    @Individual.save
    respond_to do |format|
      format.js { flash.now[:notice] = "#{@Individual.first_name} #{@Individual.last_name} has been added to the cohort" }
    end
  end

def remove_individual_from_cohort
    @Individual = Individual.find(params[:individual_id])
    @Individual.cohort_id = nil
    @Individual.save
    respond_to do |format|
      format.js { flash.now[:notice] = "#{@Individual.first_name} #{@Individual.last_name} has been removed from the cohort" }
    end
  end

def update_demographics
    @cohort = Cohort.where("id = ?", params[:cohort_id])
    respond_to do |format|
      format.js
    end
end

  # GET /individuals/1
  # GET /individuals/1.json
  def show
    if !current_user.admin? && current_user.individual != @individual
      redirect_to "/"
    end
    unless @individual.cohort_id.nil?
      @cohort = Cohort.find(@individual.cohort_id)
    end
  end

  # GET /individuals/new
  def new
    @organization = Organization.find(params[:organization_id])
    @individual = Individual.new(organization_id: params[:organization_id])
    @individual.household_members.build
  end

  # GET /individuals/1/edit
  def edit
    @organization = Organization.find(@individual.organization_id)
    unless @individual.cohort_id.nil?
      @cohort = Cohort.find(@individual.cohort_id)
    end
  end

  # POST /individuals
  # POST /individuals.json
  def create
    @organization = Organization.find_by_code(params[:individual][:code])
    @individual = Individual.new(individual_params)

    respond_to do |format|
      if @individual.save
        format.html { redirect_to @individual, notice: 'Individual was successfully created.' }
        format.json { render :show, status: :created, location: @individual }
      else
        format.html { render :new }
        format.json { render json: @individual.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /individuals/1
  # PATCH/PUT /individuals/1.json
  def update
    respond_to do |format|
      if @individual.update(individual_params)
        format.html { redirect_to @individual, notice: 'Individual was successfully updated.' }
        format.json { render :show, status: :ok, location: @individual }
      else
        format.html { render :edit }
        format.json { render json: @individual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /individuals/1
  # DELETE /individuals/1.json
  def destroy
    @individual.destroy
    respond_to do |format|
      format.html { redirect_to individuals_url, notice: 'Individual was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check_code
    @organization = Organization.find_by_code(params[:code])
    if @organization != nil
        redirect_to new_individual_path(organization_id: @organization.id)
    else
      flash[:alert] = "Sorry, I can't find that code."
      redirect_to "/"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_individual
      @individual = Individual.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def individual_params
      params.require(:individual).permit(:first_name, :last_name, :suffix, :address_line_1, :address_line_2, 
                                         :city, :state, :zip, :phone_number, :mobile_phone_number, 
                                         :email_address, :DOB, :start_date, :us_citizen, 
                                         :ethnicity, :ethnicity_other, :lanuage_primary, :language_other, 
                                         :springfield_native, :springfield_native_neighborhood, 
                                         :springfield_non_native_population, 
                                         :neighborhood_resident_length_in_months, 
                                         :springfield_non_native_distance, 
                                         :childhood_raisedby_other_than_parents, 
                                         :childhood_raisedby_other_than_parents_length_in_months, 
                                         :childhood_raisedby_other_than_parents_by_who, 
                                         :childhood_residence_away_from_family, 
                                         :childhood_residence_away_from_family_length_in_months, 
                                         :childhood_swore_at_or_put_down, 
                                         :childhood_made_to_feel_afraid_of_injury, 
                                         :childhood_pushed_shoved_grabbed_slapped, 
                                         :childhood_hit_hard, :childhood_lived_with_alcoholic, 
                                         :childhood_lived_with_drug_user, 
                                         :childhood_lived_with_depressed_or_mentally_ill, 
                                         :childhood_lived_with_member_who_attempted_suicide, 
                                         :childhood_lived_with_member_went_to_jail, 
                                         :childhood_jailed_family_member_which, 
                                         :childhood_caregiver_was_pushed_shoved_grabbed_slapped, 
                                         :childhood_caregiver_bitten_or_hit, 
                                         :childhood_caregiver_hit_repeatedly, 
                                         :childhood_caregiver_threatened_with_weapon, :cohort_id,
                                         :preferred_method_of_contact, :non_us_citizen_country_of_citizenship, 
                                         :cohort_id, :organization_id, :date_of_application, :alternate_phone, 
                                         :willing_and_able_to_commit_to_program, :specific_days_that_do_not_work, 
                                         :days_and_times_not_available, :currently_employed, :employed_full_or_part_time, 
                                         :employer, :position, :avg_hours_worked_per_week, :hourly_wage, :salary, 
                                         :employer_benefits, :not_employed_but_eligible, :how_many_jobs_in_last_six_months, 
                                         :total_family_income_from_all_sources, :child_support, :other_sources_of_income, 
                                         :currently_file_taxes, :receive_earned_income_tax_credit, 
                                         :highest_education_attained, :highest_education_attained_by_parent_or_caretaker, 
                                         :marital_status, :children_living_outside_home, :children_outside_home_who, 
                                         :parenting_class, :parenting_class_which, :quality_childcare, 
                                         :children_currently_in_quality_care, :children_in_quality_care_explain, 
                                         :have_health_care_in_some_form, :have_health_care_in_some_form_explain, 
                                         :children_have_health_care_in_some_form, 
                                         :children_have_health_care_in_some_form_explain, 
                                         :currently_have_stable_housing, :rent_or_own, 
                                         :monthly_rent_or_mortgage_payment, :receive_rent_rebate, 
                                         :currently_receive_public_housing_assistance, 
                                         :currently_receive_private_subsidized_housing_assistance, 
                                         :use_section_eight_voucher, :currently_have_reliable_transportation, 
                                         :reliable_transportation_method, :reliable_transportation_method_other, 
                                         :possible_to_obtain_reliable_transportation_in_sixty_days, 
                                         :have_required_auto_insurance, :have_valid_id_or_drivers_license, 
                                         :no_valid_id_or_license_reason, :revoked_or_suspended_license_explanation, 
                                         :ever_convicted_of_felony, :ever_convicted_of_misdemeanor, 
                                         :current_pending_court_cases, :any_legal_matters_needing_resolution, 
                                         :nwp_assets_family, :nwp_assets_lives_in_neighborhood, 
                                         :nwp_assets_accountability, :nwp_assets_parenting_training, 
                                         :nwp_assets_ged_highschool_college, :nwp_assets_transportation, 
                                         :nwp_assets_stable_housing, :nwp_assets_quality_childcare, 
                                         :nwp_assets_earned_income_tax_credit, 
                                         :nwp_assets_resolved_criminal_background_na, 
                                         :nwp_assets_monthly_budget_management, 

app/helpers/individuals_helper.rb
module IndividualsHelper
end

app/views/individuals/_form.html.erb
<%= simple_form_for(individual, html: { class: 'form-horizontal left' }, wrapper_mappings: {
    check_boxes: :vertical_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :vertical_file_input,
    boolean: :vertical_boolean
  } ) do |f| %>
     <% if individual.errors.any? %>
       <div id="error_explanation">
         <h2><%= pluralize(individual.errors.count, "error") %> prohibited this individual from being saved:</h2>

         <ul>
         <% individual.errors.full_messages.each do |message| %>
           <li><%= message %></li>
         <% end %>
         </ul>
       </div>
     <% end %>
   <fieldset>
  
   
  

  

   <%= f.hidden_field :organization_id, :value => @organization.id %>
   <%= f.button :submit %>
   </fieldset>

<% end %>

app/views/individuals/_household_member_fields.html.erb
<tr class="nested-fields">
  <td><%= f.text_field :name %></td>
  <td><%= f.text_field :relationship %></td>
  <td><%= f.text_field :age %></td>
  <td><%= f.text_field :school %></td>
  <td><%= f.text_field :care_provider %></td>
  <td><%= f.check_box :_destroy %> <%= link_to_remove_association "Remove", f %></td>
</tr>

app/views/individuals/_show_non-admin.html.erb
<p id="notice"><%= notice %></p>
  
  <h2>Hello <%= @individual.first_name %>. Thank you for participating in the Northwest Project!</h2>
  <%= "You currently are working on #{@individual.goals.count} #{"goal".pluralize(@individual.goals.count)}." %><p>
<% @individual.goals.each do |goal| %>
<div>
    <%= link_to "Goal: \"#{goal.goal}\" that was created on #{goal.created_at.strftime("%m/%d/%Y")} is currently #{goal.completion_percentage}% complete. ", edit_goal_path(goal) %>
</div>
<div class="progress">
  <div class="progress-bar" style="width: <%= goal.completion_percentage %>%;" role="progressbar" aria-valuenow="<%= goal.completion_percentage %>" aria-valuemin="0" aria-valuemax="100">
    <span class="sr-only"><%= goal.completion_percentage %>% Complete</span>
  </div>
</div>
 <% end %>

app/views/individuals/assign_cohort.html.erb
<h2>Assign individuals to <%= @cohort.meeting_night %> night cohort, that began on <%= @cohort.start_date %></h2>
<table class="table">
	<tr>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Phone</th>
		<th>Cell Phone</th>
		<th>Email</th>
		<th>Date of Birth</th>
		<th></th>
	</tr>
	<% @individuals.each do |individual| %>
	<tr id="<%= individual.id %>">
		<td><%=  individual.first_name %></td>
		<td><%=  individual.last_name %></td>
		<td><%=  individual.phone_number %></td>
		<td><%=  individual.mobile_phone_number	 %></td>
		<td><%=  individual.email_address %></td>
		<td><%=  individual.DOB %></td>
		<td><%= link_to "Assign to cohort", assign_individual_to_cohort_path(cohort_id: @cohort.id, individual_id: individual.id), remote: true %>
</td>

	</tr>
	<% end %>
</table>

  

app/views/individuals/assign_individual_to_cohort.js.erb
$("#flash").html('<%= j render partial: "shared/notice_banner" %>');
var element = document.getElementById("<%= @Individual.id %>");
element.remove();

app/views/individuals/edit.html.erb
<h1>Initial Client Data Intake</h1>

<%= render 'form', individual: @individual %>

app/views/individuals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Individuals</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>First</th>
      <th>Last</th>
      <th>Home Phone</th>
      <th>Mobile Phone</th>
      <th>Email</th>
      <th>Dob</th>
      <th>Start date</th>
      <th>Cohort</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @individuals.each do |individual| %>
      <tr>
        <td><%= individual.first_name %></td>
        <td><%= individual.last_name %></td>
        <td><%= individual.phone_number %></td>
        <td><%= individual.mobile_phone_number %></td>
        <td><%= individual.email_address %></td>
        <td><%= individual.DOB %></td>
        <td><%= individual.start_date %></td>
        <td><%= individual.cohort.try(:meeting_night) %></td>
        <td><%= link_to 'Show', individual %></td>
        <td><%= link_to 'Edit', edit_individual_path(individual) %></td>
        <td><%= link_to 'Destroy', individual, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Add Assessment', new_assessment_path(individual_id: individual.id), method: :get %></td>
        <td><%= link_to 'New Individual', new_individual_path(organization_id: current_user.organization), method: :get %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/individuals/new.html.erb
	<h1>Apply for The Northwest Project</h1>

<%= render 'form_screen', individual: @individual %>

app/views/individuals/quarterly_report.html.erb
<h2>Quarterly Report</h2>
<!-- %= select_tag 'cohort_id', options_for_select(@cohorts.map{|cohort| ["#{cohort.meeting_night} #{cohort.meeting_night}", cohort.id] }), {:include_blank => true, :class => 'form-control col-md-3', :id => 'cohort_select'} % -->

<div id="quarterly_report" class="well">
  <h1 class="text-center">Baseline Report: <%= I18n.t("date.month_names")[Date.today.month] %> <%= Date.today.year  %></h1>
  <div id="report_data">
  <h2>
	<%= Individual.where('id IN (SELECT DISTINCT(cohort_id) FROM individuals)').count %> cohorts serving <%= Individual.where("cohort_id IS NOT NULL").count %>  individuals.
  </h2>
  <% @individuals.each  do | i | %>
	  <div><h3>Affortable Housing</h3>
        <div>
        	

        </div>
	  </div>

	  <div><h3>Quality Childcare</h3>

	  </div>
	  
	  <div><h3>Transportation</h3>

	  </div>


	  <div><h3>Monthly Budget</h3></div>	


	  <div><h3>Earned Income Tax Credit</h3></div>


	  <div><h3>Resolved Criminal Issues</h3></div>


	  <div><h3>Parenting Class</h3></div>


	  <div><h3>Job Training</h3></div>


	  <div><h3>Accountability</h3></div>


	  <div><h3>Health & Well Being</h3></div>

<% end %>
  </div>
</div>

app/views/individuals/remove_individual_from_cohort.js.erb
$("#flash").html('<%= j render partial: "shared/notice_banner" %>');
var element = document.getElementById("<%= @Individual.id %>");
element.remove();

app/views/individuals/show.html.erb
<% if current_user.admin %>
  <%= render "show_admin" %>
<% else %>
  <%= render "show_non-admin" %>
<% end %>

 