config/routes.rb
require 'Nwpadmin'
Rails.application.routes.draw do


  resources :next_steps
  resources :notes
  resources :goals
  resources :attendances
  resources :meetings
  resources :individuals, :has_many => :household_members
  resources :cohorts
  resources :assessments
  resources :organizations
  constraints(Nwpadmin) do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    get '/report' => 'users#report'
  end

  match '/check_code',      to: 'individuals#check_code',        via: 'post'

  devise_for :users

  root 'static_pages#home'
  get 'static_pages/home'

  get 'static_pages/help'

  get 'individual/assign' => 'individuals#assign_cohort', :as => 'assign_cohort'
  get 'individual/assign_to_cohort' => 'individuals#assign_individual_to_cohort', :as => 'assign_individual_to_cohort'
  get 'individual/remove_from_cohort' => 'individuals#remove_individual_from_cohort', :as => 'remove_individual_from_cohort'
  get 'individual/quarterly_report' => 'individuals#quarterly_report', :as => 'quarterly_report'
  get 'individual/update_demographics' => 'individuals#update_demographics', :as => 'update_demographics'

  # Reports
  match '/reports/quarterly', to: "reports#quarterly", via: 'get'

  #constraints(Nwpadmin) do
#    get '/report' => 'users#report'
 # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organization.rb
class Organization < ApplicationRecord
	has_paper_trail
	has_many :users
	has_many :individuals
	has_many :cohorts
	
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :verify_is_admin
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    if current_user.admin?
      @organizations = Organization.all
    else
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @individuals = []
    @cohorts = @organization.cohorts.all
    @cohorts.each do |cohort| 
      cohort.individuals.each do |i|
        @individuals << i 
      end
    end
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :address_line_1, :address_line_2, :city, :state, :zip, :phone_number, :website, :primary_contact, :code)
    end

    def verify_is_admin
      (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
    end

end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= simple_form_for(organization, html: { class: 'form-horizontal left' }) do |f| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>

    <%= f.input :name %>
    <%= f.input :address_line_1 %>
    <%= f.input :address_line_2 %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :zip %>
    <%= f.input :website %>
    <%= f.input :code %>
    <%= f.input :primary_contact %>

    <%= f.button :submit %>
</fieldset>
<% end %>

app/views/organizations/edit.html.erb
<div class="well">
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

</div>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizations</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th></th>
      <th>City</th>
      <th>ST</th>
      <th>Zip</th>
      <th>Phone #</th>
      <th>Website</th>
      <th>Contact </th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.address_line_1 %></td>
        <td><%= organization.address_line_2 %></td>
        <td><%= organization.city %></td>
        <td><%= organization.state %></td>
        <td><%= organization.zip %></td>
        <td><%= organization.phone_number %></td>
        <td><%= organization.website %></td>
        <td><%= organization.primary_contact %></td>

        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Delete', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Location</h1>
<%= render 'form', organization: @organization %>

app/views/organizations/show.html.erb
<div class="well">
	<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Address Line 1:</strong>
  <%= @organization.address_line_1 %>
</p>

<p>
  <strong>Address Line 2:</strong>
  <%= @organization.address_line_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @organization.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @organization.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @organization.zip %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @organization.phone_number %>
</p>

<p>
  <strong>Website:</strong>
  <%= @organization.website %>
</p>

<p>
  <strong>New Participant Sign Up Code:</strong>
  <%= @organization.code %>
</p>

<p>
  <strong>Primary Contact:</strong>
  <%= @organization.primary_contact %>
</p>
<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %> | 
<%= link_to 'Create Cohort', new_cohort_path %>

</div>

<h3>Individuals singed up through this organziation</h3>

<table class="table table-striped">
  <tr>
    <th>Name</th><th>Phone Number</th><th>E-mail Address</th>
    </th>
  </tr>
<% @individuals.each do |i| %>
  <tr>
    <td><%= i.to_label %></td><td><%= i.phone_number %></td><td><%= i.email_address %></td>
  </tr>
<% end %>
</table>